services:
  jira-clone-db:
    image: postgres:latest
    container_name: jira-clone-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - jira-clone-db_data:/var/lib/postgresql/data

volumes:
  jira-clone-db_data:
